- name: Install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Start service
    ansible.builtin.servive:
      name: nginx
      state: started
      enabled: yes

