- name: Variables
  hosts: local   #without targeting outside server for just printing
  connection: local #to not give passwords and username
  vars:
    COURSE: "Devops"
    DURATION: "120 Hours"
    TRAINER: "Siva"
  tasks:
  - name: Printing Variables
    ansible.builtin.debug:
      msge: "Course name is: {{ COURSE }}"