- name: Variables
  hosts: local   #without targeting outside server for just printing
  connection: local #to not give passwords and username
  vars:       #play-level variables
    COURSE: "Devops"
    DURATION: "120 Hours"
    TRAINER: "Siva"
  tasks:
  - name: Printing Variables
    vars:
      COURSE: "Task level devops"
    ansible.builtin.debug:
      msg: "Course name is: {{ COURSE }}"