- name: Variables
  hosts: local   #without targeting outside server for just printing
  connection: local #to not give passwords and username
  vars_files:
  - course.yaml       #variable files 
  tasks:
  - name: Printing Variables
    ansible.builtin.debug:
      msg: "Course name is: {{ COURSE }}"