# Take input from user
- name: Taking prompt from user
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: Enter username
    private: false
  - name: password
    prompt: Enter passwords
    private: false
  tasks:
  - name: Printing username and password
    ansible.builtin.debug:
      msge: "Username is {{ username }} and password is {{ password }}"

