- name: Data types
  hosts: local
  connection: local
  vars:
    PROGRAM: "Hi, Chandana"
    DURATION: 120
    IS_LIVE: false
    DETAILS:
      MONTHS: 4
      TRAINER: "Siva"
    TOPICS:
    - Linux
    - Shell
    - Ansible
  tasks:
  - name: datatypes
    ansible.builtin.debug:
      msg: |
        Program: {{ PROGRAM }}
        Duration: {{ DURATION }}
        Is live: {{ IS_LIVE }}
        Details: {{ DETAILS }}
        Topics: {{ TOPICS }}